--CREATE DATABASE DB_TP_FRANCK;
USE DB_TP_FRANCK;
--DROP TABLE IF EXISTS EMP;
--DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT(
	DEPTNO TINYINT NOT NULL,
	DNAME VARCHAR(50) NOT NULL,
	LOC VARCHAR(50) NOT NULL,
		CONSTRAINT PK_DEPT_DEPTNO PRIMARY KEY (DEPTNO),	
);

CREATE TABLE EMP(
	EMPNO SMALLINT NOT NULL,
	ENAME VARCHAR(32) NOT NULL,
	JOB VARCHAR(32) NOT NULL,
	MGR SMALLINT,
	HIREDATE DATE NOT NULL,
	SAL MONEY,
	COMM MONEY,
	DEPTNO TINYINT NOT NULL,
		CONSTRAINT PK_EMP_EMPNO_ID PRIMARY KEY (EMPNO),
		CONSTRAINT FK_EMP_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
		CONSTRAINT FK_EMP_MGR FOREIGN KEY (MGR) REFERENCES EMP (EMPNO),
);

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'PROJET' AND xtype = 'U')
BEGIN
	CREATE TABLE PROJET(
		PROJETNO SMALLINT NOT NULL,
		PROJETNAME VARCHAR(5) NOT NULL,
		BUDGET INT NOT NULL,
			CONSTRAINT PK_PROJ_PROJETNO PRIMARY KEY (PROJETNO)
	);
END 


ALTER TABLE EMP
	ADD PROJETNO SMALLINT;
ALTER TABLE EMP
	ADD CONSTRAINT FK_EMP_PROJETNO FOREIGN KEY (PROJETNO) REFERENCES PROJET (PROJETNO);