DROP DATABASE IF EXISTS db_fly;

CREATE DATABASE db_fly;

USE db_fly;

CREATE TABLE AIRPLANES
(
AIRPLANE_REGISTRATION varchar(10) primary key,
AIRPLANE_SIZE decimal(5.2) not null,
AIRPLANE_TYPE varchar(15) not null
);

CREATE TABLE POSSESSORS
(
POSSESSOR_ID int,
POSSESSOR_AIRPLANE int not null,
POSSESSOR_AIRPLANE_TYPE varchar(15) not null,
POSSESSOR_NAME varchar(32) not null,
POSSESSOR_ADDRESS varchar (255) not null,
POSSESSOR_PHONE_NUMBER varchar(10) not null,
POSSESSOR_AIRPLANE_PURCHASE date not null,
AIRPLANE_REGISTRATION varchar(10),
primary key (AIRPLANE_REGISTRATION, POSSESSOR_ID),
foreign key(AIRPLANE_REGISTRATION) references AIRPLANES(AIRPLANE_REGISTRATION)
);

CREATE TABLE PILOTS
(
PILOT_NUMBER int primary key,
PILOT_LASTNAME varchar(32) not null,
PILOT_FIRSTNAME varchar (32) not null,
PILOT_PHONE_NUMBER varchar(10) not null,
PILOT_ADDRESS varchar(255) not null,
PILOT_TRAINING varchar (255) not null,
PILOT_HOURS_FLIGHT time not null,
PILOT_LICENSE varchar(255) not null
);

CREATE TABLE OPERATIONS
(
OPERATION_NUMBER varchar(50)primary key,
OPERATION_AIRPLANE_TYPE varchar(50)not null,
OPERATION_OBJECTIVE varchar(255) not null,
OPERATION_DURATION datetime not null
);

CREATE TABLE MECANICS
(
MECANIC_ID int primary key,
MECANIC_LASTNAME varchar(32) not null,
MECANIC_FIRSTNAME varchar(32) not null,
MECANIC_PHONE_NUMBER varchar(10),
MECANIC_ADDRESS varchar(255) not null,
MECANIC_HABILITY varchar(255) not null
);

CREATE TABLE DRIVE
(
AIRPLANE_REGISTRATION varchar(10),
PILOT_NUMBER int,
primary key(AIRPLANE_REGISTRATION, PILOT_NUMBER),
foreign key(AIRPLANE_REGISTRATION) references AIRPLANES (AIRPLANE_REGISTRATION),
foreign key (PILOT_NUMBER) references PILOTS(PILOT_NUMBER)
);

CREATE TABLE REPARE
(
AIRPLANE_REGISTRATION varchar(10),
MECANIC_ID int,
primary key (AIRPLANE_REGISTRATION, MECANIC_ID),
foreign key (AIRPLANE_REGISTRATION) references AIRPLANES (AIRPLANE_REGISTRATION),
foreign key (MECANIC_ID) references MECANICS (MECANIC_ID)
);

CREATE TABLE ORGANIZE
(
 OPERATION_NUMBER varchar(50),
 MECANIC_ID int,
 primary key (OPERATION_NUMBER, MECANIC_ID),
 foreign key (OPERATION_NUMBER) references OPERATIONS (OPERATION_NUMBER),
 foreign key (MECANIC_ID) references MECANICS (MECANIC_ID)
);